<template>
  <span class="ui-status-pill" :class="`ui-status-pill--${resolvedTone}`">
    <span class="ui-status-pill__dot" aria-hidden="true" />
    {{ labelMap[status] ?? labelMap[status.toLowerCase()] ?? labelMap[resolvedKey] ?? status }}
  </span>
</template>

<script setup lang="ts">
import { computed } from 'vue';

interface Props {
  status: string;
}

const props = defineProps<Props>();

type Tone = 'success' | 'warning' | 'error' | 'info' | 'neutral';

const statusMap: Record<Tone, string[]> = {
  success: [
    'delivered', 'ok', 'active', 'online', 'closed', 'low', 'approved',
    'completed', 'paid', 'valid', 'renewed', 'fullreceipt', 'matched',
    'readyforpayment', 'confirmed', 'selected', 'awarded', 'fullyreceived',
    'convertedtopo', 'serviceaccepted', 'scored', 'linkedtopaymentrequest',
    'signed',
  ],
  warning: [
    'in transit', 'invited', 'printing', 'medium', 'investigating',
    'pending', 'underreview', 'suspended', 'pendingapproval', 'pendingreview', 'pendingverification',
    'blockedoverbudget', 'pendingcommitteeapproval', 'underevaluation', 'pendingevaluation',
    'partiallyreceived', 'revisionrequested', 'partialreceipt',
    'mismatchexception', 'onhold', 'expiringsoon', 'pendingsignature',
    'open',
  ],
  info: [
    'picking', 'in progress', 'assigned', 'inprogress',
    'draft', 'budgetchecked', 'openforquotation', 'submitted',
    'autogenerated', 'senttovendor', 'pendingreceipt', 'created',
    'matching', 'taxvalidated', 'glallocated', 'inpaymentproposal',
    'bankfilegenerated', 'delegated', 'processingpayment',
  ],
  error: [
    'failed', 'suspended', 'offline', 'high', 'overdue', 'cancelled',
    'rejected', 'blocked', 'blacklisted', 'noaward', 'claimraised',
    'expired', 'locked', 'duplicaterejected', 'escalated', 'urgent',
  ],
  neutral: [
    'draft', 'inactive', 'superseded', 'notselected', 'original', 'amendment',
    'superceded',
  ],
};

// Thai display labels for status values (supporting lowercased lookups)
const labelMap: Record<string, string> = {
  // Vendor & General
  active: 'ใช้งาน',
  pendingregistration: 'รอตรวจอนุมัติ',
  suspended: 'ระงับชั่วคราว',
  blocked: 'ถูกบล็อก',
  blacklisted: 'แบล็คลิสต์',
  inactive: 'ไม่ใช้งาน',
  underreview: 'อยู่ระหว่างตรวจสอบ',
  
  // PR
  draft: 'ร่างเอกสาร',
  pendingapproval: 'รออนุมัติ',
  approved: 'อนุมัติแล้ว',
  rejected: 'ไม่อนุมัติ',
  cancelled: 'ยกเลิก',
  blockedoverbudget: 'งบประมาณเกิน/ติดบล็อก',
  convertedtopo: 'ออกใบสั่งซื้อแล้ว',
  
  // RFQ / Bidding
  openforquotation: 'เปิดรับซองใบเสนอราคา',
  closed: 'ปิดรับซองแล้ว',
  awarded: 'ตัดสินแล้ว',
  noaward: 'ไม่มีผู้ชนะ',
  submitted: 'ยื่นใบเสนอราคาแล้ว',
  selected: 'ผ่านการคัดเลือก',
  notselected: 'ไม่ผ่านการคัดเลือก',
  underevaluation: 'อยู่ระหว่างประเมิน',
  pendingevaluation: 'อยู่ระหว่างประเมิน',
  pendingcommitteeapproval: 'รออนุมัติจากคณะกรรมการ',
  
  // PO
  confirmed: 'ผู้ขายยืนยัน PO',
  vendorconfirmed: 'ผู้ขายยืนยัน PO',
  senttovendor: 'ส่งให้ผู้ขายแล้ว',
  partiallyreceived: 'รับบางส่วน',
  fullyreceived: 'รับสินค้าครบถ้วน',
  autogenerated: 'ออกโดยระบบอัตโนมัติ',
  revisionrequested: 'ขอแก้ไขรายการ',
  
  // GR & Claims
  pendingreceipt: 'รอตรวจรับ',
  partialreceipt: 'รับบางส่วน',
  fullreceipt: 'รับครบถ้วน',
  serviceaccepted: 'ตรวจรับบริการแล้ว',
  claimraised: 'แจ้งเคลมสินค้า',
  processed: 'ดำเนินการเคลมแล้ว',
  open: 'รอดำเนินการเคลม',
  
  // Finance & AP
  matched: 'จับคู่สำเร็จ (3-Way)',
  mismatchexception: 'ข้อมูลไม่ตรงกัน',
  readyforpayment: 'พร้อมสั่งจ่าย',
  paid: 'ชำระเงินแล้ว',
  processingpayment: 'กำลังดำเนินการจ่ายเงิน',
  onhold: 'ระงับการชำระเงิน',
  
  // Evaluation & SLA
  pendingreview: 'รอตรวจสอบ',
  pendingverification: 'รอยืนยัน',
  shortlisted: 'ผ่านคัดเลือก',
  scored: 'ประเมินแล้ว',
  linkedtopaymentrequest: 'เชื่อมโยงคำสั่งจ่ายแล้ว',
  
  // Contracts
  signed: 'ลงนามเสร็จสิ้น',
  pendingsignature: 'รอคู่ค้าลงนาม',
  superceded: 'สิ้นสุด/มีสัญญาใหม่แทนที่',
  original: 'สัญญาต้นฉบับ',
  amendment: 'สัญญาแก้ไขเพิ่มเติม',

  // Other statusMap keys to prevent English leak
  'in transit': 'อยู่ระหว่างขนส่ง',
  intransit: 'อยู่ระหว่างขนส่ง',
  'in progress': 'อยู่ระหว่างดำเนินการ',
  inprogress: 'อยู่ระหว่างดำเนินการ',
  invited: 'เชิญแล้ว',
  printing: 'กำลังพิมพ์',
  medium: 'ปานกลาง',
  investigating: 'อยู่ระหว่างตรวจสอบ',
  expiringsoon: 'ใกล้หมดอายุ',
  picking: 'กำลังจัดเตรียม',
  assigned: 'มอบหมายแล้ว',
  budgetchecked: 'ตรวจสอบงบประมาณแล้ว',
  created: 'สร้างแล้ว',
  matching: 'อยู่ระหว่างจับคู่',
  taxvalidated: 'ตรวจสอบภาษีแล้ว',
  glallocated: 'บันทึกบัญชีแล้ว',
  inpaymentproposal: 'อยู่ในข้อเสนอการสั่งจ่าย',
  bankfilegenerated: 'สร้างไฟล์สั่งจ่ายธนาคารแล้ว',
  delegated: 'มอบหมายงานต่อแล้ว',
  failed: 'ล้มเหลว',
  offline: 'ออฟไลน์',
  high: 'สูง',
  overdue: 'เกินกำหนด',
  locked: 'ถูกล็อก',
  duplicaterejected: 'ปฏิเสธรายการซ้ำ',
  escalated: 'ยกระดับสายอนุมัติ',
  urgent: 'ด่วนที่สุด',
  ok: 'ตกลง',
  delivered: 'จัดส่งแล้ว'
};

const resolvedKey = computed(() => props.status);

const resolvedTone = computed((): Tone => {
  const s = props.status.toLowerCase().replace(/\s+/g, '');
  for (const [tone, statuses] of Object.entries(statusMap) as [Tone, string[]][]) {
    if (statuses.some(st => st.replace(/\s+/g, '') === s)) {
      return tone;
    }
  }
  return 'neutral';
});
</script>

<style scoped>
.ui-status-pill {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 3px 10px;
  font-family: var(--font-sans);
  font-size: var(--text-xs);
  font-weight: var(--weight-medium);
  letter-spacing: var(--tracking-wide);
  border-radius: var(--radius-full);
  white-space: nowrap;
  line-height: var(--leading-normal);
}

.ui-status-pill__dot {
  width: 6px;
  height: 6px;
  border-radius: var(--radius-full);
  background-color: currentColor;
  flex-shrink: 0;
}

/* Tones */
.ui-status-pill--success {
  color: var(--color-success-700);
  background-color: var(--color-success-100);
}

.ui-status-pill--warning {
  color: var(--color-warning-700);
  background-color: var(--color-warning-100);
}

.ui-status-pill--error {
  color: var(--color-error-700);
  background-color: var(--color-error-100);
}

.ui-status-pill--info {
  color: var(--color-info-700);
  background-color: var(--color-info-100);
}

.ui-status-pill--neutral {
  color: var(--fg-secondary);
  background-color: var(--bg-surface);
}
</style>
