<template>
  <span
    class="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-medium border border-transparent shadow-[var(--shadow-sm)]"
    :class="badgeClass"
  >
    <span class="w-1.5 h-1.5 rounded-full bg-current opacity-70 flex-shrink-0" />
    {{ labelMap[props.status.toLowerCase()] ?? props.status }}
  </span>
</template>

<script setup lang="ts">
import { computed } from 'vue';

const props = defineProps({
  status: {
    type: String,
    required: true,
  },
});

const labelMap: Record<string, string> = {
  // Vendor
  active: 'ใช้งาน',
  inactive: 'ไม่ใช้งาน',
  pendingregistration: 'รอตรวจอนุมัติ',
  underreview: 'อยู่ระหว่างตรวจสอบ',
  suspended: 'ระงับชั่วคราว',
  blocked: 'ถูกบล็อก',
  blacklisted: 'แบล็คลิสต์',
  // PR / Approval
  draft: 'ร่างเอกสาร',
  pendingapproval: 'รออนุมัติ',
  approved: 'อนุมัติแล้ว',
  rejected: 'ไม่อนุมัติ',
  cancelled: 'ยกเลิก',
  blockedoverbudget: 'งบประมาณเกิน/ติดบล็อก',
  convertedtopo: 'ออกใบสั่งซื้อแล้ว',
  // RFQ / Bidding
  openforquotation: 'เปิดรับซองใบเสนอราคา',
  closed: 'ปิดรับซองแล้ว',
  awarded: 'ตัดสินแล้ว',
  noaward: 'ไม่มีผู้ชนะ',
  submitted: 'ยื่นใบเสนอราคาแล้ว',
  selected: 'ผ่านการคัดเลือก',
  notselected: 'ไม่ผ่านการคัดเลือก',
  underevaluation: 'อยู่ระหว่างประเมิน',
  pendingcommitteeapproval: 'รออนุมัติจากคณะกรรมการ',
  // PO
  senttovendor: 'ส่งให้ผู้ขายแล้ว',
  vendorconfirmed: 'ผู้ขายยืนยัน PO',
  confirmed: 'ผู้ขายยืนยัน PO',
  revisionrequested: 'ขอแก้ไขรายการ',
  partiallyreceived: 'รับบางส่วน',
  fullyreceived: 'รับสินค้าครบถ้วน',
  autogenerated: 'ออกโดยระบบอัตโนมัติ',
  // GR
  pendingreceipt: 'รอตรวจรับ',
  partialreceipt: 'รับบางส่วน',
  fullreceipt: 'รับครบถ้วน',
  serviceaccepted: 'ยืนยันรับงานบริการ',
  claimraised: 'แจ้งเคลมสินค้า',
  // Finance / AP
  created: 'ยื่นวางบิลแล้ว',
  matched: 'จับคู่สำเร็จ (3-Way)',
  mismatchexception: 'ข้อมูลไม่ตรงกัน',
  readyforpayment: 'พร้อมสั่งจ่าย',
  paid: 'ชำระเงินแล้ว',
  onhold: 'ระงับการชำระเงิน',
  inpaymentproposal: 'อยู่ในข้อเสนอการสั่งจ่าย',
  bankfilegenerated: 'สร้างไฟล์สั่งจ่ายธนาคารแล้ว',
  // Contracts
  signed: 'ลงนามเสร็จสิ้น',
  pendingsignature: 'รอคู่ค้าลงนาม',
  superseded: 'สิ้นสุด/มีสัญญาใหม่แทนที่',
  superceded: 'สิ้นสุด/มีสัญญาใหม่แทนที่',
  // Evaluation
  pendingreview: 'รอตรวจสอบ',
  scored: 'ประเมินแล้ว',
  // Other
  pending: 'รอดำเนินการ',
  expired: 'หมดอายุ',
  locked: 'ถูกล็อก',
  escalated: 'ยกระดับสายอนุมัติ',
  urgent: 'ด่วนที่สุด',
  completed: 'เสร็จสิ้น',
  valid: 'ใช้ได้',
  renewed: 'ต่ออายุแล้ว',
  expiringsoon: 'ใกล้หมดอายุ',
  duplicaterejected: 'ปฏิเสธรายการซ้ำ',
};

const badgeClass = computed(() => {
  const s = props.status.toLowerCase();
  if (['draft', 'budgetchecked', 'openforquotation', 'submitted', 'autogenerated', 'senttovendor', 'pendingreceipt', 'created', 'matching', 'taxvalidated', 'glallocated', 'inpaymentproposal', 'bankfilegenerated', 'delegated', 'inprogress'].includes(s)) {
    return 'bg-[var(--accent)] text-[var(--accent-foreground)]';
  }
  if (['underreview', 'suspended', 'pendingapproval', 'pendingreview', 'blockedoverbudget', 'pendingcommitteeapproval', 'underevaluation', 'partiallyreceived', 'revisionrequested', 'partialreceipt', 'mismatchexception', 'onhold', 'expiringsoon', 'pending', 'pendingsignature'].includes(s)) {
    return 'bg-[var(--warning-soft)] text-[var(--warning-soft-foreground)]';
  }
  if (['active', 'approved', 'convertedtopo', 'awarded', 'selected', 'vendorconfirmed', 'confirmed', 'fullyreceived', 'fullreceipt', 'serviceaccepted', 'scored', 'matched', 'readyforpayment', 'linkedtopaymentrequest', 'paid', 'valid', 'renewed', 'completed', 'signed'].includes(s)) {
    return 'bg-[var(--success-soft)] text-[var(--success-soft-foreground)]';
  }
  if (['rejected', 'blocked', 'blacklisted', 'noaward', 'cancelled', 'claimraised', 'failed', 'expired', 'locked', 'duplicaterejected'].includes(s)) {
    return 'bg-[var(--destructive-soft)] text-[var(--destructive-soft-foreground)]';
  }
  if (['escalated', 'urgent'].includes(s)) {
    return 'bg-[var(--urgent-soft,var(--destructive-soft))] text-[var(--urgent-soft-foreground,var(--destructive-soft-foreground))]';
  }
  return 'bg-[var(--muted)] text-[var(--muted-foreground)]';
});
</script>
