<template>
  <span 
    class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border border-transparent shadow-[var(--shadow-sm)]"
    :class="badgeClass"
  >
    <slot>{{ status }}</slot>
  </span>
</template>

<script setup lang="ts">
import { computed } from 'vue';

const props = defineProps({
  status: {
    type: String,
    required: true,
  },
});

const badgeClass = computed(() => {
  const s = props.status.toLowerCase();
  
  if (['draft', 'budgetchecked', 'openforquotation', 'submitted', 'autogenerated', 'senttovendor', 'pendingreceipt', 'created', 'matching', 'taxvalidated', 'glallocated', 'inpaymentproposal', 'bankfilegenerated', 'delegated', 'inprogress'].includes(s)) {
    return 'bg-[var(--accent)] text-[var(--accent-foreground)]';
  }
  
  if (['underreview', 'suspended', 'pendingapproval', 'blockedoverbudget', 'pendingcommitteeapproval', 'underevaluation', 'partiallyreceived', 'revisionrequested', 'partialreceipt', 'mismatchexception', 'onhold', 'expiringsoon', 'pending'].includes(s)) {
    return 'bg-[var(--warning-soft)] text-[var(--warning-soft-foreground)]';
  }
  
  if (['active', 'approved', 'convertedtopo', 'awarded', 'selected', 'vendorconfirmed', 'fullyreceived', 'fullreceipt', 'serviceaccepted', 'scored', 'matched', 'readyforpayment', 'linkedtopaymentrequest', 'confirmed', 'paid', 'valid', 'renewed', 'completed'].includes(s)) {
    return 'bg-[var(--success-soft)] text-[var(--success-soft-foreground)]';
  }
  
  if (['rejected', 'blocked', 'blacklisted', 'noaward', 'cancelled', 'claimraised', 'failed', 'expired', 'locked', 'duplicaterejected'].includes(s)) {
    return 'bg-[var(--destructive-soft)] text-[var(--destructive-soft-foreground)]';
  }
  
  if (['escalated', 'urgent'].includes(s)) {
    return 'bg-[var(--urgent-soft)] text-[var(--urgent-soft-foreground)]';
  }
  
  if (['closed', 'inactive', 'superseded', 'notselected'].includes(s)) {
    return 'bg-[var(--muted)] text-[var(--muted-foreground)]';
  }
  
  return 'bg-[var(--muted)] text-[var(--muted-foreground)]';
});
</script>
