// User Roles in the system
export enum UserRole {
  REQUESTER = 'Requester',
  BUYER = 'Buyer',
  APPROVER = 'Approver',
  WAREHOUSE = 'Warehouse',
  ACCOUNTING = 'Accounting',
  FINANCE = 'Finance',
  ADMIN = 'Admin',
}

// Vendor Status
export enum VendorStatus {
  PENDING_REGISTRATION = 'PendingRegistration',
  UNDER_REVIEW = 'UnderReview',
  ACTIVE = 'Active',
  REJECTED = 'Rejected',
  SUSPENDED = 'Suspended',
  BLOCKED = 'Blocked',
  BLACKLISTED = 'Blacklisted',
}

// Purchase Requisition Status
export enum PurchaseRequisitionStatus {
  DRAFT = 'Draft',
  BUDGET_CHECKED = 'BudgetChecked',
  PENDING_APPROVAL = 'PendingApproval',
  APPROVED = 'Approved',
  REJECTED = 'Rejected',
  BLOCKED_OVER_BUDGET = 'BlockedOverBudget',
  CONVERTED_TO_PO = 'ConvertedToPO',
  CANCELLED = 'Cancelled',
}

// Bidding Status
export enum BiddingStatus {
  DRAFT = 'Draft',
  PENDING_COMMITTEE_APPROVAL = 'PendingCommitteeApproval',
  OPEN_FOR_QUOTATION = 'OpenForQuotation',
  CLOSED = 'Closed',
  UNDER_EVALUATION = 'UnderEvaluation',
  AWARDED = 'Awarded',
  NO_AWARD = 'NoAward',
  REJECTED = 'Rejected',
}

// Bid Quotation Status
export enum BidQuotationStatus {
  SUBMITTED = 'Submitted',
  SELECTED = 'Selected',
  NOT_SELECTED = 'NotSelected',
  SUPERSEDED = 'Superseded',
}

// Purchase Order Status
export enum PurchaseOrderStatus {
  AUTO_GENERATED = 'AutoGenerated',
  PENDING_APPROVAL = 'PendingApproval',
  APPROVED = 'Approved',
  REJECTED = 'Rejected',
  SENT_TO_VENDOR = 'SentToVendor',
  VENDOR_CONFIRMED = 'VendorConfirmed',
  PARTIALLY_RECEIVED = 'PartiallyReceived',
  FULLY_RECEIVED = 'FullyReceived',
  REVISION_REQUESTED = 'RevisionRequested',
  PROCESSING_PAYMENT = 'ProcessingPayment',
  PAID = 'Paid',
  CLOSED = 'Closed',
  CANCELLED = 'Cancelled',
}

// Goods Receipt Status
export enum GoodsReceiptStatus {
  PENDING_RECEIPT = 'PendingReceipt',
  PARTIAL_RECEIPT = 'PartialReceipt',
  FULL_RECEIPT = 'FullReceipt',
  SERVICE_ACCEPTED = 'ServiceAccepted',
  SCORED = 'Scored',
  CLAIM_RAISED = 'ClaimRaised',
  CLOSED = 'Closed',
}

// Claim Status
export enum ClaimStatus {
  OPEN = 'Open',
  IN_PROGRESS = 'InProgress',
  CLOSED = 'Closed',
}

// Return Note Status
export enum ReturnNoteStatus {
  PENDING = 'Pending',
  COMPLETED = 'Completed',
}

// Invoice Status
export enum InvoiceStatus {
  CREATED = 'Created',
  DUPLICATE_REJECTED = 'DuplicateRejected',
  MATCHING = 'Matching',
  MATCHED = 'Matched',
  MISMATCH_EXCEPTION = 'MismatchException',
  TAX_VALIDATED = 'TaxValidated',
  GL_ALLOCATED = 'GLAllocated',
  READY_FOR_PAYMENT = 'ReadyForPayment',
  LINKED_TO_PAYMENT_REQUEST = 'LinkedToPaymentRequest',
}

// Payment Request Status
export enum PaymentRequestStatus {
  CREATED = 'Created',
  BUDGET_CHECKED = 'BudgetChecked',
  PENDING_APPROVAL = 'PendingApproval',
  BLOCKED_OVER_BUDGET = 'BlockedOverBudget',
  VERIFIED = 'Verified',
  APPROVED_TO_CONFIRM = 'ApprovedToConfirm',
  CONFIRMED = 'Confirmed',
  IN_PAYMENT_PROPOSAL = 'InPaymentProposal',
  ON_HOLD = 'OnHold',
  BANK_FILE_GENERATED = 'BankFileGenerated',
  PAID = 'Paid',
  FAILED = 'Failed',
  REJECTED = 'Rejected',
}

// Vendor Document Status
export enum VendorDocumentStatus {
  VALID = 'Valid',
  EXPIRING_SOON = 'ExpiringSoon',
  EXPIRED = 'Expired',
}

// Item Price Status
export enum ItemPriceStatus {
  ACTIVE = 'Active',
  EXPIRING_SOON = 'ExpiringSoon',
  EXPIRED = 'Expired',
}

// Contract Status
export enum ContractStatus {
  ACTIVE = 'Active',
  RENEWED = 'Renewed',
  EXPIRED = 'Expired',
}

// App User Status
export enum AppUserStatus {
  ACTIVE = 'Active',
  LOCKED = 'Locked',
  INACTIVE = 'Inactive',
}

// Integration Log Status
export enum IntegrationLogStatus {
  SUCCESS = 'Success',
  FAILED = 'Failed',
  RETRYING = 'Retrying',
}

export interface UserProfile {
  userId: string;
  username: string;
  email: string;
  role: UserRole;
  companyId: string;
  buId: string;
}
